// Generated by CoffeeScript 1.6.3
/*

  Faviconr

  Andrey Popp (c) 2013
*/

var checkRel, express, findFavicon, hyperquest, requestFavicon, sax, url;

url = require('url');

express = require('express');

hyperquest = require('hyperquest');

sax = require('sax');

checkRel = function(v) {
  return v === 'icon' || v === 'shortcut' || v === 'shortcut icon' || v === 'icon shortcut';
};

findFavicon = function(cb) {
  var parser;
  parser = sax.createStream(false);
  parser.on('error', function(err) {
    return cb(err);
  });
  parser.on('opentag', function(node) {
    if (node.name === 'LINK' && checkRel(node.attributes.REL)) {
      return cb(null, node.attributes.HREF);
    }
  });
  parser.on('end', function(node) {
    return cb(null);
  });
  return parser;
};

requestFavicon = function(uri, cb) {
  return hyperquest.get({
    uri: uri
  }, function(err, response) {
    if (err) {
      return cb(err);
    }
    if (/3\d\d/.exec(response.statusCode)) {
      return requestFavicon(response.headers.location, cb);
    } else if (/2\d\d/.exec(response.statusCode)) {
      return cb(null, uri);
    } else {
      return cb(null);
    }
  });
};

module.exports = function() {
  var app, cache;
  cache = {};
  app = express();
  app.get('/', function(req, res) {
    var host, protocol, _ref;
    if (req.query.url == null) {
      return res.send(400, 'provide URL as url param');
    }
    if (cache[req.query.url] != null) {
      return res.send(cache[req.query.url]);
    }
    _ref = url.parse(req.query.url), host = _ref.host, protocol = _ref.protocol;
    return requestFavicon("" + protocol + "//" + host + "/favicon.ico", function(err, icon) {
      if (icon) {
        cache[req.query.url] = icon;
        return res.send(icon);
      } else {
        return hyperquest({
          uri: req.query.url,
          method: 'GET'
        }).pipe(findFavicon(function(err, icon) {
          if (err || (icon == null)) {
            return res.send(404);
          } else {
            icon = url.resolve(req.query.url, icon);
            cache[req.query.url] = icon;
            return res.send(icon);
          }
        }));
      }
    });
  });
  return app;
};
